# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c350a4cbd51eb09620aa1e39f1abca1714a3f0650a6df77ca870bdfee94e4d7f942902f565167d1f217212392a73a402487a2283b55e6014dc0064781d32451b

test:
  secret_key_base: edb1d59fcc6783e3f37c4655873956153ea35c2db7499ea773ff3c91797bfd9d66f1cd6127a010bc22cf68cd9aaf7bf90294b76729b23bf002a82c53760aa769

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
